// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Codecool.PeerMentors.Migrations
{
    public partial class RenameUserProjectsAndUserTechnologiesTagProperty : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserProjects_Projects_ProjectID",
                table: "UserProjects");

            migrationBuilder.DropForeignKey(
                name: "FK_UserTechonologies_Techonologies_TechnologyID",
                table: "UserTechonologies");

            migrationBuilder.DropIndex(
                name: "IX_UserTechonologies_TechnologyID",
                table: "UserTechonologies");

            migrationBuilder.DropIndex(
                name: "IX_UserProjects_ProjectID",
                table: "UserProjects");

            migrationBuilder.DropColumn(
                name: "TechnologyID",
                table: "UserTechonologies");

            migrationBuilder.DropColumn(
                name: "ProjectID",
                table: "UserProjects");

            migrationBuilder.AddColumn<int>(
                name: "TagID",
                table: "UserTechonologies",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "TagID",
                table: "UserProjects",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserTechonologies_TagID",
                table: "UserTechonologies",
                column: "TagID");

            migrationBuilder.CreateIndex(
                name: "IX_UserProjects_TagID",
                table: "UserProjects",
                column: "TagID");

            migrationBuilder.AddForeignKey(
                name: "FK_UserProjects_Projects_TagID",
                table: "UserProjects",
                column: "TagID",
                principalTable: "Projects",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_UserTechonologies_Techonologies_TagID",
                table: "UserTechonologies",
                column: "TagID",
                principalTable: "Techonologies",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserProjects_Projects_TagID",
                table: "UserProjects");

            migrationBuilder.DropForeignKey(
                name: "FK_UserTechonologies_Techonologies_TagID",
                table: "UserTechonologies");

            migrationBuilder.DropIndex(
                name: "IX_UserTechonologies_TagID",
                table: "UserTechonologies");

            migrationBuilder.DropIndex(
                name: "IX_UserProjects_TagID",
                table: "UserProjects");

            migrationBuilder.DropColumn(
                name: "TagID",
                table: "UserTechonologies");

            migrationBuilder.DropColumn(
                name: "TagID",
                table: "UserProjects");

            migrationBuilder.AddColumn<int>(
                name: "TechnologyID",
                table: "UserTechonologies",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ProjectID",
                table: "UserProjects",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserTechonologies_TechnologyID",
                table: "UserTechonologies",
                column: "TechnologyID");

            migrationBuilder.CreateIndex(
                name: "IX_UserProjects_ProjectID",
                table: "UserProjects",
                column: "ProjectID");

            migrationBuilder.AddForeignKey(
                name: "FK_UserProjects_Projects_ProjectID",
                table: "UserProjects",
                column: "ProjectID",
                principalTable: "Projects",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_UserTechonologies_Techonologies_TechnologyID",
                table: "UserTechonologies",
                column: "TechnologyID",
                principalTable: "Techonologies",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
